[build]
  command = "gridsome build"
  publish = "dist"

[[redirects]]
  from = "/home/"
  to= "/"
  status = 200
  
[[redirects]]
  from = "/contact/"
  to= "/#contacts"
  status = 200

[[redirects]]
  from = "/portfolio-item/*"
  to= "/projects/:splat"
  status = 200